title: Показатель
sections:
  main:
    display: Содержание
    fields:
      - handle: label
        type: text
        display: Название показателя
        localizable: true
        required: true
      - handle: unit
        type: text
        display: Единица измерения
        localizable: true
        max: 50
  sidebar:
    display: Публикация
    fields:
      - handle: status
        type: status
        display: Статус
      - handle: value
        type: text
        display: Значение
        required: true
        max: 50
      - handle: year
        type: number
        display: Год
        min: 1900
        max: 2200
      - handle: sort_order
        type: number
        display: Порядок
